source:
  path: "data/raw/retail_sales.csv"
  chunk_size: 5000

target:
  engine: "postgresql"   # change to "duckdb" if no Postgres
  target:
  engine: "postgresql"
  conn_str: "postgresql+psycopg2://postgres:postgres@localhost:5432/Retail"
  table: "fact_sales"
  pk: ["order_id"]


options:
  fail_on_missing: ["order_id","order_date","customer_id","quantity","unit_price"]
  date_columns: ["order_date"]
